### ISSUE TITLE
Merge this repo with https://github.com/Qiskit-Partners/qiskit-aqt-provider ?

### ISSUE THREAD

**Issue by mtreinish** [alpine-quantum-technologies/qiskit-aqt-provider-rc#69]
### What is the expected behavior?

I just found this repo and I was wondering if we want to merge this into https://github.com/Qiskit-Partners/qiskit-aqt-provider ? It looks like the git history has forked from the current state of that repo. I've been maintaining the original aqt provider in my spare time (which admittedly is pretty scare nowadays) and obviously don't have the same level of access to the aqt platform. I would be very much in favor of migrating the changes here into the original repo and letting you all take over maintaining the package. I think it would be a good if we continue publishing under the existing package moving forward to enable so existing users don't have to take manual steps when upgrading.

**Comment by alfrisch** [comment]
Great that you agree with merging this into the original repo, as this is our intention too!

After the recent activities with the AQT provider we put together this release candidate repo as a first step and basis for discussions.

**Comment by airwoodix** [comment]
Thanks a lot for the offer @mtreinish! We're also surely very happy to take over maintenance of `Qiskit-Partners/qiskit-aqt-provider` if it suits you.

To add to @alfrisch's feedback:

Since release 0.10.0, the `qiskit-aqt-provider-rc` is not compatible anymore with the currently publicly accessible AQT computing portal. To avoid confusion, we'd prefer to delay merging the packages under the simpler name `qiskit-aqt-provider` until the new API, currently under development, is publicly available. Would this work for you?

We could surely improve on documentation and compliance with the Qiskit ecosystem in the meantime. Is there something in particular you'd like to see implemented / changed before the merge?

**Comment by airwoodix** [comment]
Update: we'd be happy to move forward on merging back to the original repository with qiskit-community/qiskit-aqt-provider#61.

**Comment by airwoodix** [comment]
Done through qiskit-community/qiskit-aqt-provider#61.
